### ISSUE TITLE
when vm status is shut off at first time. second backup will not processed

### ISSUE THREAD

**Issue by ENO2019** [abbbi/virtnbdbackup#104]
When the vm status is shut off . I perform the first backup operation. 
virtnbdbackup will action by copy model
Then I perform the second backup operation. 

`Cant execute switch to auto incremental backup: target folder seems not to include full backup.`

thanks. this app is very nice :)

**Comment by abbbi** [comment]
yes, if a virtual machine is shutoff, virtnbdbackup can only perform type copy backups! In order to create checkpoints and the required bitmaps in the qcow image, the virtual machine must be powered on, its not possible to create a checkpoint while the virtual machine is running:

```
virsh checkpoint-create vm1
error: Operation not supported: cannot create checkpoint for inactive domain

```
So what happens is that there is an copy backup created instead of a full backup, but for subsequent increment
backups an full backup with checkpoint is required, so this is desired behavior.
