### ISSUE TITLE
Question about CBT/Dirty Blocks

### ISSUE THREAD

**Issue by madmax01** [abbbi/virtnbdbackup#51]
@abbbi  Hello,

the Program looks very interesting.

what i think is from quick look > its may complex to handle "Traditional Backups" when lots activities

- Full Backup
- then Diff or Inc
- then archive/retention
---------------------------------------

is there may any chance a Feature Request to an real "CBT" Modern Backup Method + Retention Logic.

CBT Modern Backup =  its always a Full Backup... just new blocks getting backed up and merged into Base.

when restoring seeing only 1x backup set. .... rather into diff/inc complexity.

when restoring a VM from vmare for example i always see only 1 Image.

may kinda Idea can be done on Linux with this App also?.

**Comment by abbbi** [comment]
hi,

sorry, i dont think i completely understand your point here. In fact, virtnbdbackup does create backups based on CBT, and
it does exactly what you are describing.

The first full backup will backup all required dirty blocks to a given directory, subsequent calls with backup mode incremental or differencial (to the same backup target directory) will only backup the changes since the last full or incremental (if it is supported
by the libvirt/qemu and qcow image version you are using).

If you restore,it will automatically roll back the changes from all available backups (full + inc) and will create an qcow image with the latest contents.

**Comment by abbbi** [comment]
1) you create a full backup virtnbdbackup -d vm -l full -o /tmp/BACKUP

-> from this point on you can create incremental backups as long as you like to the same folder:

1) you create a full backup virtnbdbackup -d vm -l inc -o /tmp/BACKUP

-> only deltas are now saved. Of course you need to specify the backup mode, virtnbdbackup does currently not decide
by itself to switch to mode incremental if there is already a full backup in /tmp/BACKUP/
-> you can repeat that step for months, but what happens if your full backup gets corrupted after 3 weeks because you have
an disk failure on your target backup? You lose the possibility to restore the complete virtual machine.

Thus it is of course recommended to take another full backup in certain time frames if you want to be sure your
data is save. "Retention" thus is as simple as rotating the target directory and specifiying another backup mode.

**Comment by madmax01** [comment]
thx @abbbi 

that's the Reason why i ment > it's may interesting to change the Behavior from Traditional Style away to modern. 

in modern Way peoples don't need to care about if its full/diff or finc.... its always a Full Backup > because CBT does the Work and set shows always only 1x Full backups as all is merged. you may don't like to care about if you're "Restore" is save yes/no because you always have Backups X ;) .


is just an Idea.. Respect you're Way

**Comment by abbbi** [comment]
See: https://github.com/abbbi/virtnbdbackup#rotating-backups
